# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import video_pb2 as video__pb2


class VideoProcessingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitFrame = channel.unary_unary(
                '/videoProcessing.VideoProcessing/SubmitFrame',
                request_serializer=video__pb2.SubmitFrameRequest.SerializeToString,
                response_deserializer=video__pb2.SubmitFrameResponse.FromString,
                )
        self.Subscribe = channel.unary_stream(
                '/videoProcessing.VideoProcessing/Subscribe',
                request_serializer=video__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=video__pb2.SubscribeResponse.FromString,
                )


class VideoProcessingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoProcessingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitFrame,
                    request_deserializer=video__pb2.SubmitFrameRequest.FromString,
                    response_serializer=video__pb2.SubmitFrameResponse.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=video__pb2.SubscribeRequest.FromString,
                    response_serializer=video__pb2.SubscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'videoProcessing.VideoProcessing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoProcessing(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/videoProcessing.VideoProcessing/SubmitFrame',
            video__pb2.SubmitFrameRequest.SerializeToString,
            video__pb2.SubmitFrameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/videoProcessing.VideoProcessing/Subscribe',
            video__pb2.SubscribeRequest.SerializeToString,
            video__pb2.SubscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
