/**
 * @fileoverview gRPC-Web generated client stub for videoProcessing
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: video.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.videoProcessing = require('./video_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.videoProcessing.VideoProcessingClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.videoProcessing.VideoProcessingPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.videoProcessing.SubmitFrameRequest,
 *   !proto.videoProcessing.SubmitFrameResponse>}
 */
const methodDescriptor_VideoProcessing_SubmitFrame = new grpc.web.MethodDescriptor(
  '/videoProcessing.VideoProcessing/SubmitFrame',
  grpc.web.MethodType.UNARY,
  proto.videoProcessing.SubmitFrameRequest,
  proto.videoProcessing.SubmitFrameResponse,
  /**
   * @param {!proto.videoProcessing.SubmitFrameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.videoProcessing.SubmitFrameResponse.deserializeBinary
);


/**
 * @param {!proto.videoProcessing.SubmitFrameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.videoProcessing.SubmitFrameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.videoProcessing.SubmitFrameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.videoProcessing.VideoProcessingClient.prototype.submitFrame =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/videoProcessing.VideoProcessing/SubmitFrame',
      request,
      metadata || {},
      methodDescriptor_VideoProcessing_SubmitFrame,
      callback);
};


/**
 * @param {!proto.videoProcessing.SubmitFrameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.videoProcessing.SubmitFrameResponse>}
 *     Promise that resolves to the response
 */
proto.videoProcessing.VideoProcessingPromiseClient.prototype.submitFrame =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/videoProcessing.VideoProcessing/SubmitFrame',
      request,
      metadata || {},
      methodDescriptor_VideoProcessing_SubmitFrame);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.videoProcessing.SubscribeRequest,
 *   !proto.videoProcessing.SubscribeResponse>}
 */
const methodDescriptor_VideoProcessing_Subscribe = new grpc.web.MethodDescriptor(
  '/videoProcessing.VideoProcessing/Subscribe',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.videoProcessing.SubscribeRequest,
  proto.videoProcessing.SubscribeResponse,
  /**
   * @param {!proto.videoProcessing.SubscribeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.videoProcessing.SubscribeResponse.deserializeBinary
);


/**
 * @param {!proto.videoProcessing.SubscribeRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.videoProcessing.SubscribeResponse>}
 *     The XHR Node Readable Stream
 */
proto.videoProcessing.VideoProcessingClient.prototype.subscribe =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/videoProcessing.VideoProcessing/Subscribe',
      request,
      metadata || {},
      methodDescriptor_VideoProcessing_Subscribe);
};


/**
 * @param {!proto.videoProcessing.SubscribeRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.videoProcessing.SubscribeResponse>}
 *     The XHR Node Readable Stream
 */
proto.videoProcessing.VideoProcessingPromiseClient.prototype.subscribe =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/videoProcessing.VideoProcessing/Subscribe',
      request,
      metadata || {},
      methodDescriptor_VideoProcessing_Subscribe);
};


module.exports = proto.videoProcessing;

